version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # porta AMQP
      - "15672:15672"   # painel de gerenciamento
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-worker
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
    # Exemplo: se seu script principal for worker.py
    command: ["python", "worker.py"]
